Downgrade css-loader to < 3.0.0
To workaround
```
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
```

Some silly package of us is not up-to-date and still sends
`exportOnlyLocals` to `css-loader` thus raising this error. I don't know
which, so I'll downgrade css-loader to `2.x.x` which has the old API.