Add missing dependencies:
* string-hash
* tiptap
* tiptap-extensions

@appinteractive I see this error in docker environment:

```
webapp_1  |  FATAL  [
webapp_1  |   Error: Cannot resolve "@nuxtjs/style-resources" from "/nitro-web/nuxtjs/style-resources"
webapp_1  |       at Resolver.resolvePath (/nitro-web/node_modules/@nuxt/core/dist/core.js:487:11)
webapp_1  |       at Resolver.requireModule (/nitro-web/node_modules/@nuxt/core/dist/core.js:498:27)
webapp_1  |       at ModuleContainer.addModule (/nitro-web/node_modules/@nuxt/core/dist/core.js:145:36)
webapp_1  |       at promise.then (/nitro-web/node_modules/@nuxt/common/dist/common.js:1321:43)
webapp_1  |       at process._tickCallback (internal/process/next_tick.js:68:7)
webapp_1  |       at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
webapp_1  |       at startup (internal/bootstrap/node.js:283:19)
webapp_1  |       at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3),
webapp_1  |   [Error: Cannot find module '@nuxtjs/style-resources'] {
webapp_1  |       at new <anonymous> (/nitro-web/node_modules/esm/esm.js:1:50548)
webapp_1  |       at el (/nitro-web/node_modules/esm/esm.js:1:195465)
webapp_1  |       at /nitro-web/node_modules/esm/esm.js:1:215841
webapp_1  |       at Su (/nitro-web/node_modules/esm/esm.js:1:215921)
webapp_1  |       at qa (/nitro-web/node_modules/esm/esm.js:1:187511)
webapp_1  |       at Eu (/nitro-web/node_modules/esm/esm.js:1:217149)
webapp_1  |       at Module.<anonymous> (/nitro-web/node_modules/esm/esm.js:1:250405)
webapp_1  |       at Resolver.o [as esm] (/nitro-web/node_modules/esm/esm.js:1:235191)
webapp_1  |       at Resolver.requireModule (/nitro-web/node_modules/@nuxt/core/dist/core.js:508:31)
webapp_1  |       at ModuleContainer.addModule (/nitro-web/node_modules/@nuxt/core/dist/core.js:145:36)
webapp_1  |       at promise.then (/nitro-web/node_modules/@nuxt/common/dist/common.js:1321:43)
webapp_1  |       at process._tickCallback (internal/process/next_tick.js:68:7)
webapp_1  |       at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
webapp_1  |       at startup (internal/bootstrap/node.js:283:19)
webapp_1  |       at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
webapp_1  |     code: 'MODULE_NOT_FOUND'
webapp_1  |   }
```